### ISSUE TITLE
Test Mbaza on Windows

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/mbaza#343]
On a Windows machine:
1. Checkout the `main` branch and create an installer with `npm run package`.
2. Install Mbaza and launch it.
3. Go to media tools page. You should see a message about missing models. Unpack [models](https://drive.google.com/file/d/14piQssz64jlgS31FtMy9x0L3soJAiZ5T/view?usp=sharing) into the linked directory.
4. Test the whole application: media tools, inference, results explorer. Report any issues found here.

**Comment by oluwakemi-dada** [comment]
**Media tools**
@jchojna 

![Screenshot (457)](https://user-images.githubusercontent.com/58976869/187429478-f7be312e-d1bf-43ed-abf9-b5b621307d88.png)
![Screenshot (458)](https://user-images.githubusercontent.com/58976869/187429489-1f948933-e292-4781-8940-5f79fa74bea4.png)
![Screenshot (462)](https://user-images.githubusercontent.com/58976869/187429521-cda82874-923a-4224-8c56-cc928378dae3.png)

**Comment by oluwakemi-dada** [comment]
![Screenshot (460)](https://user-images.githubusercontent.com/58976869/187429786-d5492fa7-4b0d-45c4-870e-d47941241ef5.png)
![Screenshot (461)](https://user-images.githubusercontent.com/58976869/187429793-6eb7d9f5-1324-4a75-ab44-1c4ce14e0ed2.png)
