### ISSUE TITLE
Rare species counter

### ISSUE THREAD

**Issue by swiezew** [Appsilon/mbaza#61]
## Basic functionality
- [ ] for the count of rare species, use the list of species from [IUCN Red List](https://www.iucnredlist.org/), as proposed by Robbie, that is: 
- **Gabon**: Cat_Golden, Chimpanzee, Duiker_Yellow_Backed, Elephant_African, Gorilla, Leopard_African, Mandrillus, Pangolin
- **Serengeti**: cheetah, elephant, giraffe, hippopotamus, hyenastriped, koribustard, leopard, lionfemale, lionmale, rhinoceros, secretarybird, topi, vulture

- [ ] provide an explanation in an infobox (available on hover), or "about" section on which species are selected and why. The above were chosen since they are endangered, vulnerable or near threatened (see [this Slack thread](https://appsilon.slack.com/archives/CSXRVP7SP/p1591605644031100))

## Extended functionality
- [ ] on click in the "rare species found" change the selection of the species viewed in the species dropdown to the relevant rare ones.

**Comment by kamilzyla** [comment]
Hey @rcwhytock, is this issue still relevant?
