### ISSUE TITLE
Data explorer – map

### ISSUE THREAD

**Issue by tadeuszbaraslupski** [Appsilon/mbaza#7]
The map should show points where the animal was present. The points’ size should be scaled according to the number of individual images taken within the chosen time period. Upon clicking any given point, a window should pop up with related pictures and descriptions. The descriptions should come from the underlying CSV/Excel/data structure – i.e. species name, number of individuals, etc.

There should be an option to easily save the map – .jpg or .png for copying into a word processor.

**Comment by kamilzyla** [comment]
A map with results explorer is already implemented.
