### ISSUE TITLE
Downscale images before feeding them to the classifier

### ISSUE THREAD

**Issue by kamilzyla** [Appsilon/mbaza#78]
The classifier crashes when processing larger data sets (#74). Downscaling the images before feeding them to the classifier should hopefully solve the issue.

**Comment by swiezew** [comment]
@kamilzyla I think it won't solve the issue.
1. When we load the models using fastai's load_learner, it knows what the config of the databunch we used for training was and sets the config for the test set accordingly. In Serengeti we have trained with the final size of (384, 512), while in Gabon with (576, 768). Hence, it runs inference on images resized to that size.
2. Of course, if we feed large images, the resizing as mentioned above should take more time. We could in principle do downsizing ourselves, and hope it is going to be quicker than fastai's, but this seems like a tough challenge.
3. I've added control of the batch size during testing (default is 64), apparently the lower the batch size the faster the inference (at least on my machine- with no GPU), but most importantly, I assume RAM is used less heavily. Will commit this for you to test on your machine.
