### ISSUE TITLE
Image Exif data update

### ISSUE THREAD

**Issue by tadeuszbaraslupski** [Appsilon/mbaza#9]
A nice-to-have option where the user can tell the application to update the images classified by the model with location data (not always present in the images, because of e.g. faulty GPS units in the camera traps) and perhaps species names – to be discussed with Robbie.

Message from Robbie: "The only other thing I can think of is to check the date and time are correct. Often people make mistakes when they set the camera, and we check this by taking a photo of a blackboard with the time and date of deployment written on it. I've made a simple GUI that loads the first ten images of the 'check' the user then slides to the image with the blackboard and checks it matches the time in the exif. This will be easier to understand if I send you some screenshots, will do now. Also, if this is too tricky then please don't treat it as a priority!"

Here's a proper description of the problem we might want to resolve in this issue: https://docs.google.com/document/d/1Tv0mR6fyTrHEwgaI7yh27JNYFzErtIbc2dXYD-Om9ho/edit#heading=h.qjod6ia0n33w

**Comment by kamilzyla** [comment]
Hey @rcwhytock, is this issue still relevant?
